/**
 * Meshes — every piece of traversal geometry, generated in code.
 *
 * Nothing here is loaded, nothing here is PBR, and nothing here reaches the
 * scene without going through `finalizeGeometry`. That last one is not a style
 * note: the inverted-hull outline reads `aSmoothNormal` and `aCurvature`, and a
 * geometry that skipped the weld draws with a torn hull at every hard edge and
 * full stroke weight everywhere — the documented "exploded mesh" defect.
 *
 * DRAW-CALL BUDGET
 *
 * A course-length rail network is hundreds of objects and the main pass is
 * already the frame's cost centre, so furniture is merged into CHUNKS of route
 * distance — one mesh per (material, chunk) — and whole chunks are switched off
 * by `setWindow` as the player moves. That gives coarse culling that actually
 * removes draw calls, which per-object frustum culling on a merged mesh cannot.
 */

import {
  BufferAttribute,
  BufferGeometry,
  BoxGeometry,
  ConeGeometry,
  CylinderGeometry,
  Group,
  Object3D,
  OctahedronGeometry,
  TetrahedronGeometry,
  TorusGeometry,
  Vector3,
} from 'three';

import type { CelOptions } from '../npr/CelMaterial';
import { CelMaterial, disposeCelMaterial, makeCelMesh } from '../npr/CelMaterial';
import { finalizeGeometry } from '../npr/OutlineGeometry';
import { RAMPS } from '../npr/Palette';

export type RampName = keyof typeof RAMPS;

// ─────────────────────────────────────────────────────────────────────────────
// Merge
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Concatenate geometries that share a material. Position/normal/uv only —
 * everything the cel pipeline needs beyond that is generated by
 * `finalizeGeometry` AFTER the merge, which is also the only way the weld can
 * see across the seam between two merged parts.
 */
export function mergeGeos(parts: BufferGeometry[]): BufferGeometry {
  let vcount = 0;
  let icount = 0;
  for (const p of parts) {
    if (!p.getAttribute('normal')) p.computeVertexNormals();
    if (!p.getAttribute('uv')) {
      p.setAttribute('uv', new BufferAttribute(new Float32Array(p.getAttribute('position').count * 2), 2));
    }
    vcount += p.getAttribute('position').count;
    icount += p.getIndex() ? p.getIndex()!.count : p.getAttribute('position').count;
  }

  const position = new Float32Array(vcount * 3);
  const normal = new Float32Array(vcount * 3);
  const uv = new Float32Array(vcount * 2);
  const index = vcount > 65535 ? new Uint32Array(icount) : new Uint16Array(icount);

  let vo = 0;
  let io = 0;
  for (const p of parts) {
    const pp = p.getAttribute('position') as BufferAttribute;
    const pn = p.getAttribute('normal') as BufferAttribute;
    const pu = p.getAttribute('uv') as BufferAttribute;
    position.set(pp.array as Float32Array, vo * 3);
    normal.set(pn.array as Float32Array, vo * 3);
    uv.set(pu.array as Float32Array, vo * 2);
    const pi = p.getIndex();
    if (pi) {
      for (let i = 0; i < pi.count; i++) index[io + i] = pi.getX(i) + vo;
      io += pi.count;
    } else {
      for (let i = 0; i < pp.count; i++) index[io + i] = i + vo;
      io += pp.count;
    }
    vo += pp.count;
    p.dispose();
  }

  const g = new BufferGeometry();
  g.setAttribute('position', new BufferAttribute(position, 3));
  g.setAttribute('normal', new BufferAttribute(normal, 3));
  g.setAttribute('uv', new BufferAttribute(uv, 2));
  g.setIndex(new BufferAttribute(index, 1));
  return g;
}

// ─────────────────────────────────────────────────────────────────────────────
// Chunked mesh builder
// ─────────────────────────────────────────────────────────────────────────────

interface Bucket {
  key: string;
  preset: RampName;
  opts: CelOptions;
  chunk: number;
  parts: BufferGeometry[];
}

interface BuiltChunk {
  group: Object3D;
  chunk: number;
}

/** Metres of route distance per visibility chunk. */
const CHUNK_METRES = 220;

export class MeshBuilder {
  private buckets = new Map<string, Bucket>();
  private built: BuiltChunk[] = [];
  private materials: CelMaterial[] = [];
  private geometries: BufferGeometry[] = [];
  private visibleRange = Infinity;

  constructor(readonly object: Object3D) {}

  /**
   * Queue a geometry. `tag` selects the material bucket, so two calls with the
   * same tag must want the same preset AND the same options.
   */
  add(geo: BufferGeometry, preset: RampName, tag: string, routeDistance: number, opts: CelOptions = {}): void {
    const chunk = Math.max(0, Math.floor(routeDistance / CHUNK_METRES));
    const key = `${tag}#${chunk}`;
    let b = this.buckets.get(key);
    if (!b) {
      b = { key, preset, opts, chunk, parts: [] };
      this.buckets.set(key, b);
    }
    b.parts.push(geo);
  }

  build(): void {
    for (const b of this.buckets.values()) {
      if (b.parts.length === 0) continue;
      const geo = mergeGeos(b.parts);
      // Hard-surface weld: creases sharper than 78 degrees stay sharp, so a
      // rail's cap does not smear into its tube.
      finalizeGeometry(geo, { tolerance: 5e-4, maxWeldAngle: 78, ao: true, aoStrength: 0.5 });
      const name = b.key.replace('#', '-');
      const built = makeCelMesh(geo, b.preset, { vertexAo: true, ...b.opts, name });
      built.mesh.castShadow = true;
      built.mesh.receiveShadow = true;
      this.materials.push(built.material);
      this.geometries.push(geo);
      this.object.add(built.group);
      this.built.push({ group: built.group, chunk: b.chunk });
    }
    this.buckets.clear();
  }

  /** Show only the chunks within `range` metres of route distance `d`. */
  setWindow(d: number, range: number): void {
    if (range === this.visibleRange && range === Infinity) return;
    this.visibleRange = range;
    const c = d / CHUNK_METRES;
    const span = range / CHUNK_METRES + 1;
    for (let i = 0; i < this.built.length; i++) {
      const b = this.built[i];
      b.group.visible = Math.abs(b.chunk + 0.5 - c) <= span;
    }
  }

  dispose(): void {
    for (const m of this.materials) disposeCelMaterial(m);
    for (const g of this.geometries) g.dispose();
    this.materials.length = 0;
    this.geometries.length = 0;
    this.built.length = 0;
    this.object.clear();
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Primitive builders
// ─────────────────────────────────────────────────────────────────────────────

const _right = new Vector3();
const _u = new Vector3();
const _t = new Vector3();

/**
 * A closed tube swept along an explicit centreline with an explicit up per
 * node. Written by hand rather than with `TubeGeometry` because the rail's
 * frame comes from the track's banked up vector, and `TubeGeometry`'s Frenet
 * frame rolls unpredictably through an inflection — which on a rail reads as
 * the grind stripe spiralling.
 */
export function tubeGeometry(
  centres: Vector3[],
  ups: Vector3[],
  radius: number,
  radial = 6,
  cap = true,
): BufferGeometry {
  const n = centres.length;
  const verts = new Float32Array(n * radial * 3);
  const norms = new Float32Array(n * radial * 3);
  const uvs = new Float32Array(n * radial * 2);
  const idx: number[] = [];

  let run = 0;
  for (let i = 0; i < n; i++) {
    // Tangent by central difference so the ring is square to the path.
    const a = centres[Math.max(0, i - 1)];
    const b = centres[Math.min(n - 1, i + 1)];
    _t.subVectors(b, a);
    if (_t.lengthSq() < 1e-10) _t.set(0, 0, 1);
    _t.normalize();
    _u.copy(ups[Math.min(i, ups.length - 1)]);
    _u.addScaledVector(_t, -_u.dot(_t));
    if (_u.lengthSq() < 1e-8) _u.set(0, 1, 0).addScaledVector(_t, -_t.y);
    _u.normalize();
    _right.crossVectors(_u, _t).normalize();

    if (i > 0) run += centres[i].distanceTo(centres[i - 1]);

    for (let k = 0; k < radial; k++) {
      const ang = (k / radial) * Math.PI * 2;
      const cx = Math.cos(ang);
      const sy = Math.sin(ang);
      const nx = _right.x * cx + _u.x * sy;
      const ny = _right.y * cx + _u.y * sy;
      const nz = _right.z * cx + _u.z * sy;
      const o = (i * radial + k) * 3;
      verts[o] = centres[i].x + nx * radius;
      verts[o + 1] = centres[i].y + ny * radius;
      verts[o + 2] = centres[i].z + nz * radius;
      norms[o] = nx; norms[o + 1] = ny; norms[o + 2] = nz;
      const o2 = (i * radial + k) * 2;
      uvs[o2] = run * 0.25;
      uvs[o2 + 1] = k / radial;
    }
  }

  for (let i = 0; i < n - 1; i++) {
    for (let k = 0; k < radial; k++) {
      const k2 = (k + 1) % radial;
      const a = i * radial + k;
      const b = i * radial + k2;
      const c = (i + 1) * radial + k;
      const d = (i + 1) * radial + k2;
      idx.push(a, c, b, b, c, d);
    }
  }

  const geo = new BufferGeometry();
  geo.setAttribute('position', new BufferAttribute(verts, 3));
  geo.setAttribute('normal', new BufferAttribute(norms, 3));
  geo.setAttribute('uv', new BufferAttribute(uvs, 2));
  geo.setIndex(idx);

  if (cap) {
    // Fan caps, welded in as separate geometry so the ends read as solid.
    const caps: BufferGeometry[] = [geo];
    for (const end of [0, n - 1]) {
      const fan = new BufferGeometry();
      const fv = new Float32Array((radial + 1) * 3);
      const fn = new Float32Array((radial + 1) * 3);
      const fu = new Float32Array((radial + 1) * 2);
      const c = centres[end];
      const a = centres[Math.max(0, end - 1)];
      const b = centres[Math.min(n - 1, end + 1)];
      _t.subVectors(b, a);
      if (_t.lengthSq() < 1e-10) _t.set(0, 0, 1);
      _t.normalize();
      const sgn = end === 0 ? -1 : 1;
      fv[0] = c.x; fv[1] = c.y; fv[2] = c.z;
      fn[0] = _t.x * sgn; fn[1] = _t.y * sgn; fn[2] = _t.z * sgn;
      const fi: number[] = [];
      for (let k = 0; k < radial; k++) {
        const src = (end * radial + k) * 3;
        fv[(k + 1) * 3] = verts[src];
        fv[(k + 1) * 3 + 1] = verts[src + 1];
        fv[(k + 1) * 3 + 2] = verts[src + 2];
        fn[(k + 1) * 3] = _t.x * sgn; fn[(k + 1) * 3 + 1] = _t.y * sgn; fn[(k + 1) * 3 + 2] = _t.z * sgn;
        fu[(k + 1) * 2] = 0; fu[(k + 1) * 2 + 1] = 0;
        const k2 = ((k + 1) % radial) + 1;
        if (sgn > 0) fi.push(0, k + 1, k2);
        else fi.push(0, k2, k + 1);
      }
      fan.setAttribute('position', new BufferAttribute(fv, 3));
      fan.setAttribute('normal', new BufferAttribute(fn, 3));
      fan.setAttribute('uv', new BufferAttribute(fu, 2));
      fan.setIndex(fi);
      caps.push(fan);
    }
    return mergeGeos(caps);
  }

  return geo;
}

/** A vertical strut from `top` down to `baseY`, slightly tapered. */
export function strutGeometry(top: Vector3, baseY: number, radius = 0.10): BufferGeometry {
  const h = Math.max(0.3, top.y - baseY);
  const g = new CylinderGeometry(radius, radius * 1.55, h, 6, 1, false);
  g.translate(top.x, baseY + h * 0.5, top.z);
  return g;
}

/** A flat quad slab, `w` by `h`, centred at the origin, facing +Z. */
export function slabGeometry(w: number, h: number, thickness: number): BufferGeometry {
  return new BoxGeometry(w, h, thickness);
}

/** An upward chevron, pointing +Z, lying in the XZ plane. */
export function chevronGeometry(width: number, length: number, thickness: number): BufferGeometry {
  const g = new BufferGeometry();
  const hw = width * 0.5;
  const inner = width * 0.24;
  const pts = [
    0, 0, length * 0.5,
    -hw, 0, -length * 0.5,
    -hw + inner, 0, -length * 0.5,
    0, 0, length * 0.5 - inner * 1.6,
    hw - inner, 0, -length * 0.5,
    hw, 0, -length * 0.5,
  ];
  const v: number[] = [];
  const nrm: number[] = [];
  const uv: number[] = [];
  const idx: number[] = [];
  for (let s = 0; s < 2; s++) {
    const y = s === 0 ? thickness : 0;
    for (let i = 0; i < 6; i++) {
      v.push(pts[i * 3], y, pts[i * 3 + 2]);
      nrm.push(0, s === 0 ? 1 : -1, 0);
      uv.push(0, 0);
    }
  }
  // Top face (0..5) and bottom face (6..11), as two quads each.
  const tri = (a: number, b: number, c: number) => idx.push(a, b, c);
  tri(0, 1, 2); tri(0, 2, 3); tri(0, 3, 4); tri(0, 4, 5);
  tri(6, 8, 7); tri(6, 9, 8); tri(6, 10, 9); tri(6, 11, 10);
  // Rim so the chevron has thickness in silhouette.
  for (let i = 0; i < 6; i++) {
    const j = (i + 1) % 6;
    tri(i, j, i + 6);
    tri(j, j + 6, i + 6);
  }
  g.setAttribute('position', new BufferAttribute(new Float32Array(v), 3));
  g.setAttribute('normal', new BufferAttribute(new Float32Array(nrm), 3));
  g.setAttribute('uv', new BufferAttribute(new Float32Array(uv), 2));
  g.setIndex(idx);
  g.computeVertexNormals();
  return g;
}

/** A torus for dash rings. Radius in the XY plane, hole facing +Z. */
export function ringGeometry(radius: number, tube: number): BufferGeometry {
  return new TorusGeometry(radius, tube, 6, 24);
}

/** A cone, apex up, for spring caps. */
export function coneGeometry(radius: number, height: number): BufferGeometry {
  const g = new ConeGeometry(radius, height, 8, 1);
  g.translate(0, height * 0.5, 0);
  return g;
}

/** A short cylinder pad, base at y=0. */
export function padGeometry(radius: number, height: number, segments = 12): BufferGeometry {
  const g = new CylinderGeometry(radius, radius * 1.08, height, segments, 1);
  g.translate(0, height * 0.5, 0);
  return g;
}

/** A helical coil, for spring bodies. */
export function coilGeometry(radius: number, height: number, turns: number, wire: number): BufferGeometry {
  const centres: Vector3[] = [];
  const ups: Vector3[] = [];
  const steps = Math.max(12, Math.round(turns * 12));
  for (let i = 0; i <= steps; i++) {
    const u = i / steps;
    const a = u * turns * Math.PI * 2;
    centres.push(new Vector3(Math.cos(a) * radius, u * height, Math.sin(a) * radius));
    ups.push(new Vector3(0, 1, 0));
  }
  return tubeGeometry(centres, ups, wire, 5, false);
}

/** The common collectible: a faceted octahedron. */
export function fragmentGeometry(size: number): BufferGeometry {
  return new OctahedronGeometry(size, 0);
}

/** The rare collectible: a longer, sharper crystal. */
export function shardGeometry(size: number): BufferGeometry {
  const g = new OctahedronGeometry(size, 0);
  g.scale(0.62, 1.75, 0.62);
  return g;
}

/** A blunt tetra for cells and charges. */
export function cellGeometry(size: number): BufferGeometry {
  return new TetrahedronGeometry(size, 0);
}

export { Group };
