/**
 * CollisionWorld — a triangle soup with per-triangle surface flags, indexed by a
 * uniform grid.
 *
 * Why triangles and not boxes: the stage is full of banked curves, ramps,
 * curved pipe tops and cylindrical towers. A box solver would need a special
 * case for each; triangles handle all of them with one code path, and because
 * every mesh in the game is generated by the Kit, the collision data comes for
 * free from the same call that makes the visual.
 *
 * The capsule is approximated by a stack of overlapping spheres. Sphere-vs-
 * triangle closest-point is short, branch-light and numerically well behaved,
 * which matters far more here than the last 2% of accuracy.
 *
 * ZERO allocation after build(). All scratch state is preallocated.
 */
import { SpatialHash } from '../core/SpatialHash';
import { SF } from './Types';

export interface CapsuleHit {
  grounded: boolean;
  /** world Y of the surface under the feet when grounded */
  groundY: number;
  gnx: number; gny: number; gnz: number;
  groundFlags: number;
  wall: boolean;
  wnx: number; wny: number; wnz: number;
  wallFlags: number;
  /** how vertical the wall is: 1 = perfectly vertical */
  wallVert: number;
  ceiling: boolean;
  contacts: number;
  pushX: number; pushY: number; pushZ: number;
  /** union of all flags touched this resolve */
  touched: number;
}

export function newHit(): CapsuleHit {
  return {
    grounded: false, groundY: 0, gnx: 0, gny: 1, gnz: 0, groundFlags: 0,
    wall: false, wnx: 0, wny: 0, wnz: 0, wallFlags: 0, wallVert: 0,
    ceiling: false, contacts: 0, pushX: 0, pushY: 0, pushZ: 0, touched: 0,
  };
}

/** cos of the steepest angle still considered floor (≈ 50°) */
const GROUND_DOT = 0.64;
/** anything flatter than this in Y is a wall (≈ 65°+) */
const WALL_DOT = 0.42;

export class CollisionWorld {
  private cap = 0;
  private tri = new Float32Array(0);   // 9 floats / tri
  private nrm = new Float32Array(0);   // 3 floats / tri
  private flg = new Uint8Array(0);
  private box = new Float32Array(0);   // 6 floats / tri
  count = 0;
  readonly hash = new SpatialHash(6);
  built = false;

  // scratch
  private cpx = 0; private cpy = 0; private cpz = 0;

  constructor(initial = 65536) { this.grow(initial); }

  private grow(n: number) {
    if (n <= this.cap) return;
    const c = Math.max(n, Math.ceil(this.cap * 1.7) + 1024);
    const t = new Float32Array(c * 9); t.set(this.tri); this.tri = t;
    const m = new Float32Array(c * 3); m.set(this.nrm); this.nrm = m;
    const f = new Uint8Array(c); f.set(this.flg); this.flg = f;
    const b = new Float32Array(c * 6); b.set(this.box); this.box = b;
    this.cap = c;
  }

  clear() { this.count = 0; this.built = false; }

  /** Add one world-space triangle. Winding determines the normal (CCW = front). */
  addTri(
    ax: number, ay: number, az: number,
    bx: number, by: number, bz: number,
    cx: number, cy: number, cz: number,
    flags: number,
  ) {
    // reject degenerate triangles early — they produce NaN normals
    const e1x = bx - ax, e1y = by - ay, e1z = bz - az;
    const e2x = cx - ax, e2y = cy - ay, e2z = cz - az;
    let nx = e1y * e2z - e1z * e2y;
    let ny = e1z * e2x - e1x * e2z;
    let nz = e1x * e2y - e1y * e2x;
    const l = Math.sqrt(nx * nx + ny * ny + nz * nz);
    if (l < 1e-9) return;
    nx /= l; ny /= l; nz /= l;

    this.grow(this.count + 1);
    const i = this.count++;
    const o = i * 9;
    const t = this.tri;
    t[o] = ax; t[o + 1] = ay; t[o + 2] = az;
    t[o + 3] = bx; t[o + 4] = by; t[o + 5] = bz;
    t[o + 6] = cx; t[o + 7] = cy; t[o + 8] = cz;
    const p = i * 3;
    this.nrm[p] = nx; this.nrm[p + 1] = ny; this.nrm[p + 2] = nz;
    this.flg[i] = flags;
    const q = i * 6;
    this.box[q] = Math.min(ax, bx, cx); this.box[q + 1] = Math.min(ay, by, cy); this.box[q + 2] = Math.min(az, bz, cz);
    this.box[q + 3] = Math.max(ax, bx, cx); this.box[q + 4] = Math.max(ay, by, cy); this.box[q + 5] = Math.max(az, bz, cz);
    this.built = false;
  }

  build() {
    this.hash.build(this.box, this.count);
    this.built = true;
  }

  triFlags(i: number) { return this.flg[i]; }

  /** Closest point on triangle `i` to (px,py,pz). Result in this.cp*. */
  private closest(i: number, px: number, py: number, pz: number) {
    const t = this.tri, o = i * 9;
    const ax = t[o], ay = t[o + 1], az = t[o + 2];
    const bx = t[o + 3], by = t[o + 4], bz = t[o + 5];
    const cx = t[o + 6], cy = t[o + 7], cz = t[o + 8];

    const abx = bx - ax, aby = by - ay, abz = bz - az;
    const acx = cx - ax, acy = cy - ay, acz = cz - az;
    const apx = px - ax, apy = py - ay, apz = pz - az;
    const d1 = abx * apx + aby * apy + abz * apz;
    const d2 = acx * apx + acy * apy + acz * apz;
    if (d1 <= 0 && d2 <= 0) { this.cpx = ax; this.cpy = ay; this.cpz = az; return; }

    const bpx = px - bx, bpy = py - by, bpz = pz - bz;
    const d3 = abx * bpx + aby * bpy + abz * bpz;
    const d4 = acx * bpx + acy * bpy + acz * bpz;
    if (d3 >= 0 && d4 <= d3) { this.cpx = bx; this.cpy = by; this.cpz = bz; return; }

    const vc = d1 * d4 - d3 * d2;
    if (vc <= 0 && d1 >= 0 && d3 <= 0) {
      const v = d1 / (d1 - d3);
      this.cpx = ax + abx * v; this.cpy = ay + aby * v; this.cpz = az + abz * v; return;
    }

    const cpx2 = px - cx, cpy2 = py - cy, cpz2 = pz - cz;
    const d5 = abx * cpx2 + aby * cpy2 + abz * cpz2;
    const d6 = acx * cpx2 + acy * cpy2 + acz * cpz2;
    if (d6 >= 0 && d5 <= d6) { this.cpx = cx; this.cpy = cy; this.cpz = cz; return; }

    const vb = d5 * d2 - d1 * d6;
    if (vb <= 0 && d2 >= 0 && d6 <= 0) {
      const w = d2 / (d2 - d6);
      this.cpx = ax + acx * w; this.cpy = ay + acy * w; this.cpz = az + acz * w; return;
    }

    const va = d3 * d6 - d5 * d4;
    if (va <= 0 && (d4 - d3) >= 0 && (d5 - d6) >= 0) {
      const w = (d4 - d3) / ((d4 - d3) + (d5 - d6));
      this.cpx = bx + (cx - bx) * w; this.cpy = by + (cy - by) * w; this.cpz = bz + (cz - bz) * w; return;
    }

    const denom = 1 / (va + vb + vc);
    const v = vb * denom, w = vc * denom;
    this.cpx = ax + abx * v + acx * w;
    this.cpy = ay + aby * v + acy * w;
    this.cpz = az + abz * v + acz * w;
  }

  /**
   * Depenetrate a capsule and report what it touched.
   *
   * @param p  [x,y,z] feet position — MUTATED in place
   * @param r  radius
   * @param h  total height (feet to crown)
   */
  resolveCapsule(p: Float32Array, r: number, h: number, out: CapsuleHit, iterations = 4): CapsuleHit {
    out.grounded = false; out.wall = false; out.ceiling = false; out.contacts = 0;
    out.groundFlags = 0; out.wallFlags = 0; out.touched = 0; out.wallVert = 0;
    out.gnx = 0; out.gny = 1; out.gnz = 0;
    out.wnx = 0; out.wny = 0; out.wnz = 0;
    out.pushX = 0; out.pushY = 0; out.pushZ = 0;
    out.groundY = -1e9;
    if (!this.built || this.count === 0) return out;

    const nSph = Math.max(2, Math.ceil((h - 2 * r) / (r * 0.92)) + 1);
    const y0 = r, y1 = h - r;
    let bestGY = -1e9, bestGDot = GROUND_DOT;
    let bestWDot = 1e9;

    for (let it = 0; it < iterations; it++) {
      const n = this.hash.query(p[0] - r - 0.6, p[2] - r - 0.6, p[0] + r + 0.6, p[2] + r + 0.6);
      let moved = 0;
      for (let s = 0; s < nSph; s++) {
        const sy = p[1] + (nSph === 1 ? (y0 + y1) * 0.5 : y0 + (y1 - y0) * (s / (nSph - 1)));
        const sx = p[0], sz = p[2];
        for (let k = 0; k < n; k++) {
          const ti = this.hash.out[k];
          const q = ti * 6;
          // cheap AABB reject
          if (this.box[q] > sx + r || this.box[q + 3] < sx - r) continue;
          if (this.box[q + 1] > sy + r || this.box[q + 4] < sy - r) continue;
          if (this.box[q + 2] > sz + r || this.box[q + 5] < sz - r) continue;

          this.closest(ti, sx, sy, sz);
          let dx = sx - this.cpx, dy = sy - this.cpy, dz = sz - this.cpz;
          let d2 = dx * dx + dy * dy + dz * dz;
          if (d2 >= r * r) continue;

          const pi = ti * 3;
          const tnx = this.nrm[pi], tny = this.nrm[pi + 1], tnz = this.nrm[pi + 2];
          let d = Math.sqrt(d2);
          if (d < 1e-6) { dx = tnx; dy = tny; dz = tnz; d = 1e-6; }
          else { dx /= d; dy /= d; dz /= d; }
          // always push along the *triangle* normal side we're on, so we never
          // get sucked through a face when deeply penetrating
          if (dx * tnx + dy * tny + dz * tnz < 0) { dx = tnx; dy = tny; dz = tnz; }

          const pen = r - d;
          const fl = this.flg[ti];
          out.touched |= fl;
          out.contacts++;

          if (tny >= GROUND_DOT) {
            // floor
            const topY = this.cpy;
            if (topY > bestGY) { bestGY = topY; out.gnx = tnx; out.gny = tny; out.gnz = tnz; out.groundFlags = fl; }
            if (tny > bestGDot) bestGDot = tny;
            out.grounded = true;
          } else if (tny <= -0.5) {
            out.ceiling = true;
          } else if (Math.abs(tny) < WALL_DOT) {
            const vert = 1 - Math.abs(tny);
            if (vert < bestWDot || !out.wall) {
              out.wall = true; out.wnx = tnx; out.wny = tny; out.wnz = tnz;
              out.wallFlags = fl; out.wallVert = vert; bestWDot = vert;
            }
          }

          if (pen > 0) {
            const k2 = pen + 1e-4;
            p[0] += dx * k2; p[1] += dy * k2; p[2] += dz * k2;
            out.pushX += dx * k2; out.pushY += dy * k2; out.pushZ += dz * k2;
            moved += pen;
          }
        }
      }
      if (moved < 1e-4) break;
    }
    out.groundY = bestGY;
    return out;
  }

  /**
   * Downward probe used for ground snapping and shadow placement.
   * Returns distance to the surface or -1.
   */
  groundProbe(x: number, y: number, z: number, maxDown: number, out: CapsuleHit | null = null): number {
    return this.raycastDown(x, y, z, maxDown, out);
  }

  private rcNx = 0; private rcNy = 0; private rcNz = 0; private rcFlags = 0;
  get hitNx() { return this.rcNx; } get hitNy() { return this.rcNy; }
  get hitNz() { return this.rcNz; } get hitFlags() { return this.rcFlags; }

  raycastDown(x: number, y: number, z: number, maxDown: number, out: CapsuleHit | null = null): number {
    if (!this.built) return -1;
    const n = this.hash.query(x - 0.05, z - 0.05, x + 0.05, z + 0.05);
    let best = maxDown;
    let found = false;
    for (let k = 0; k < n; k++) {
      const ti = this.hash.out[k];
      const q = ti * 6;
      if (this.box[q] > x || this.box[q + 3] < x) continue;
      if (this.box[q + 2] > z || this.box[q + 5] < z) continue;
      if (this.box[q + 1] > y || this.box[q + 4] < y - maxDown) continue;
      const t = this.rayTri(ti, x, y, z, 0, -1, 0, best);
      if (t >= 0 && t < best) { best = t; found = true; if (out) { out.gnx = this.rcNx; out.gny = this.rcNy; out.gnz = this.rcNz; out.groundFlags = this.rcFlags; } }
    }
    return found ? best : -1;
  }

  /** General ray query. Returns t (distance) or -1. Normal in hitNx/y/z. */
  raycast(ox: number, oy: number, oz: number, dx: number, dy: number, dz: number, maxT: number): number {
    if (!this.built) return -1;
    // walk the ray's XZ footprint as one query rect (rays here are short)
    const ex = ox + dx * maxT, ez = oz + dz * maxT;
    const n = this.hash.query(Math.min(ox, ex) - 0.2, Math.min(oz, ez) - 0.2, Math.max(ox, ex) + 0.2, Math.max(oz, ez) + 0.2);
    let best = maxT, found = false;
    let bnx = 0, bny = 0, bnz = 0, bf = 0;
    for (let k = 0; k < n; k++) {
      const ti = this.hash.out[k];
      const t = this.rayTri(ti, ox, oy, oz, dx, dy, dz, best);
      if (t >= 0 && t < best) { best = t; found = true; bnx = this.rcNx; bny = this.rcNy; bnz = this.rcNz; bf = this.rcFlags; }
    }
    this.rcNx = bnx; this.rcNy = bny; this.rcNz = bnz; this.rcFlags = bf;
    return found ? best : -1;
  }

  /** Möller–Trumbore, double sided. */
  private rayTri(i: number, ox: number, oy: number, oz: number, dx: number, dy: number, dz: number, maxT: number): number {
    const t = this.tri, o = i * 9;
    const ax = t[o], ay = t[o + 1], az = t[o + 2];
    const e1x = t[o + 3] - ax, e1y = t[o + 4] - ay, e1z = t[o + 5] - az;
    const e2x = t[o + 6] - ax, e2y = t[o + 7] - ay, e2z = t[o + 8] - az;
    const px = dy * e2z - dz * e2y, py = dz * e2x - dx * e2z, pz = dx * e2y - dy * e2x;
    const det = e1x * px + e1y * py + e1z * pz;
    if (det > -1e-9 && det < 1e-9) return -1;
    const inv = 1 / det;
    const tx = ox - ax, ty = oy - ay, tz = oz - az;
    const u = (tx * px + ty * py + tz * pz) * inv;
    if (u < -1e-5 || u > 1.00001) return -1;
    const qx = ty * e1z - tz * e1y, qy = tz * e1x - tx * e1z, qz = tx * e1y - ty * e1x;
    const v = (dx * qx + dy * qy + dz * qz) * inv;
    if (v < -1e-5 || u + v > 1.00001) return -1;
    const tt = (e2x * qx + e2y * qy + e2z * qz) * inv;
    if (tt < 1e-4 || tt > maxT) return -1;
    const pi = i * 3;
    this.rcNx = this.nrm[pi]; this.rcNy = this.nrm[pi + 1]; this.rcNz = this.nrm[pi + 2];
    this.rcFlags = this.flg[i];
    return tt;
  }

  /** True if the straight line between two points is unobstructed (homing LOS). */
  lineClear(ax: number, ay: number, az: number, bx: number, by: number, bz: number): boolean {
    const dx = bx - ax, dy = by - ay, dz = bz - az;
    const len = Math.sqrt(dx * dx + dy * dy + dz * dz);
    if (len < 1e-4) return true;
    return this.raycast(ax, ay, az, dx / len, dy / len, dz / len, len - 0.15) < 0;
  }

  get memoryMB() { return (this.tri.byteLength + this.nrm.byteLength + this.box.byteLength + this.flg.byteLength) / 1048576; }
}

export { SF };
